# This workflow will do a clean install of node dependencies, build the source code, run tests and deploy (if pushing to main branch)
# For more information see: - https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions 
#                           - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Build, Test and Deploy

on: push

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Clean install service dependencies
      run: npm ci
    - name: Unit tests
      run: npm run test

  deploy:
    name: Deploy
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install serverless
      run: npm install -g serverless
    - name: Configure serverless
      run: serverless config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    - name: Deploy Lambda functions
      run: serverless deploy
