# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment to AWS lambda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  serverless-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install serverless
      run: npm install -g serverless
   # - run: npm run build --if-present
   # - run: npm test
    - name: Configure serverless
      run: serverless config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    - name: Deploy Lambda functions
      run: serverless deploy
